### PR TITLE
Added sanity check in get_member

### PR DESCRIPTION
**Pull request by lfdversluis**
Watch it burn.

### CODE REVIEW

**Comment by lfdversluis** [comment]
FAILED (SKIP=4, errors=396)

**Comment by lfdversluis** [comment]
Might be old unmaintained code. It never gets called in current devel.

**Comment by whirm** [comment]
Thanks for checking. Let's see if I manage to have a look at it on Monday

**Comment by devos50** [comment]
@qstokkink and I found out what was wrong: the check assumes that `my_member` of a community has an associated dispersy-identity message in the database but this is not always true when we put this check inside the `get_member` method.

**Pull request closed without merging**
