### PR TITLE
Improve discovery

### PR DESCRIPTION
**Pull request by NielsZeilemaker**

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
@whirm it's ready, but its a bit worrying that the test_bootstrap failed twice. Any clue if we can get it to show some output? The output of the tracker?

**Comment by whirm** [comment]
@NielsZeilemaker I will check later

**Comment by NielsZeilemaker** [comment]
I've discovered a small bug in the bootstrap unit-test, let me fix that first. Then this pull request should be ready to merge.

**Comment by NielsZeilemaker** [comment]
@whirm I've added some logging which hopefully will help us determine why some of the introduction requests are malformed in the discovery community.
It's ready to be merged.

**Pull request merged**
