### PR TITLE
Fixes undefined local variable.

### PR DESCRIPTION
**Pull request by boudewijn-tribler**

### CODE REVIEW

**Comment by boudewijn-tribler** [comment]
Once merged, the Tribler next branch must be updated to include this fix.

**Comment by whirm** [comment]
you should do it the other way around, fixes to tribler next and then merge to devel, or we have to manually cherry pick the fix commits.

**Comment by synctext** [comment]
So we should have also a Dispersy "next" branch? Or just have Tribler Next point here?
Currently that Dispersy branch does not exist. That also would mean some extensions to Jenkins (Dispersy_test for: master,Devel,Next). Is that what you prefer Whirm?

**Comment by whirm** [comment]
We can create the next branch the moment we need to stabilize Dispersy while developing new features. We are not in a rush right now.
Edit: I see we have the cleanup pull request pending, so maybe it is a good moment to create the next branch now.

**Pull request merged**
