### PR TITLE
WIP: Updated the documentation

### PR DESCRIPTION
**Pull request by Jumba**
I fixed some errors in the document with the help of Martijn, and clarified the installation process a bit more at steps where I got stuck.

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
@Jumba thanks! Please mark the PR as READY in the title when it's ready for a review.

**Comment by devos50** [comment]
@Jumba is this ready?

**Comment by synctext** [comment]
@Jumba  just hearing from our master student @YourDaddyIsHere that he has tried your minimal community example on his Ubuntu 16.04 box. Sadly it fails. 

@YourDaddyIsHere Perhaps a simple install error, can you post the error?

**Comment by YourDaddyIsHere** [comment]
@Jumba, where should I put those files (ExampleCommunity, ExamplePayload,etc)? in the root directory (~/tribler/Tribler/dispersy) of dispersy? And I should always run python xxx.py in  tribler root directory (~/tribler)?

I try the original example (in the documentation of dispersy) and it throws an error in dispersy.py in the line "from .authentication import xxxxx.....", it says "attempt relative import to non-package". (I put the files in ~/tribler/Tribler/dispersy, and I try the "python ..." command in ~/tribler,~/tribler/Tribler and ~/tribler/Tribler/dispersy, they all throws this error) do you meet the same error when you run the original example?

**Comment by devos50** [comment]
Closing this one in favour of #528

**Pull request closed without merging**
