### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by mitchellolsthoorn**

### CODE REVIEW

**Comment by synctext** [comment]
@qstokkink  These bachlor students are creating a decentral market community in Dispersy. Their first sprint is creating docs.. Can you help a bit and give them some feedback?

**Comment by synctext** [comment]
instead of ==challenged networks== in the intro, refer to "integrated NAT puncturing" please. Remove space and vanet examples, just focus on consumers behind NAT boxes.
Perhaps insert a picture..

remove the "Anonymous" in subsection title

**Comment by qstokkink** [comment]
Already much better than the old docs.
Some things that caught my eye, mostly nitpicking:
- [_README.rst_] "a large lumber of nodes"
- [_README.rst_] For some reason the list of key features does not render as a list on GitHub
- [_README.rst_] The "ReadTheDocs" link doesn't work
- [_system_overview.rst_] Two instances of "stuble difference" (stumble difference, error in old doc as well)
- [_system_overview.rst_] In the "Who to walk to" section: the list is broken on the word "predefined"
- [_usage.rst_] "When a message is send or received" should be "When a message is sent or received"
- [_usage.rst_] "the an implemented-message" should be "the implemented message"
- There are some empty sections in _wire_protocol.rst_ and _usage.rst_ (most importantly the "Run Twisted in a separate thread" section)

To avoid merge conflict hell: are you still actively working on this?

**Comment by synctext** [comment]
please make another PR for above remarks. much better docs now

**Comment by mitchellolsthoorn** [comment]
@qstokkink We are still going to make improvements to the docs and also incorporate the feedback. We will make another PR for it, as Johan suggested. To make the readthedocs link work, the repo has to be imported into readthedocs.org. Do want me to do that or someone from the core Tribler team?

**Comment by qstokkink** [comment]
@mitchellolsthoorn From reading about readthedocs I can't see any reason why you shouldn't be the one to import it. If there are any weird ownership constraints I missed, you might want to confer with @synctext about who should own the documentation.

**Comment by mitchellolsthoorn** [comment]
@synctext Can you make an account on readthedocs, so I can at you as an owner. Readthedocs also needs a webhook, which I don't have permission for to create, so once I added you, can you create this?

**Comment by whirm** [comment]
@mitchellolsthoorn give me the link the instructions and I'll take care of the hooks.

**Comment by mitchellolsthoorn** [comment]
@whirm the instructions can be found at [readthedocs ](http://read-the-docs.readthedocs.org/en/latest/webhooks.html) in the github section

**Comment by whirm** [comment]
Ok, I've added the hooks for the dispersy, tribler and gumby repos

**Comment by mitchellolsthoorn** [comment]
@whirm thx

**Pull request merged**
