### PR TITLE
Fixed discovery community

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Compare the sum_of_statistics graphs of:
http://jenkins.tribler.org/job/Experiment_Discovery/78/
http://jenkins.tribler.org/job/Experiment_Discovery/83/
and
http://jenkins.tribler.org/job/Experiment_Discovery/104/

The discovery community was broken for at least 3 months, but probably longer. Implemented a unit-test to prevent this from happening again.

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by NielsZeilemaker** [comment]
@whirm ready

**Comment by synctext** [comment]
wow!

**Comment by whirm** [comment]
@NielsZeilemaker nice!

**Pull request merged**
