### PR TITLE
Fixed/extended doublememberauth

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
When a message is modified, the sender signature is reset. But if accepted unmodified, then both signatures would be set after Bob accepts it.

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
@whirm ready

**Comment by synctext** [comment]
Morning, Thnx for refactor!

Can the outgoing signature-request contain a signed msg, extended by receiver with more info and double signed upon return signature-response..

**Comment by NielsZeilemaker** [comment]
The outgoing message contains a signature, but it's reset after Bob modifies the message. Alice will sign it again after accepting the modifications of Bob.

**Comment by NielsZeilemaker** [comment]
@whirm I'm thinking to not call the callback from here: https://github.com/Tribler/dispersy/blob/devel/community.py#L2431
if the message did not change, as by then we already have a valid double signed message.

**Comment by whirm** [comment]
@NielsZeilemaker sound good to me.

**Comment by NielsZeilemaker** [comment]
Ok, I'll create another pull request for that one. Let's merge this one to let @snorberhuis continue testing his community.

**Pull request merged**
