### PR TITLE
modified endpoint communication with libswift

### PR DESCRIPTION
**Pull request by badrock**
DO NOT MERGE YET!!
changed init of dispersy prefix registration

!works only with the latest versions of swift/tribler

### CODE REVIEW

**Comment by synctext** [comment]
ok to test this

**Comment by synctext** [comment]
retest this please

**Comment by badrock** [comment]
As the comment says: "DO NOT MERGE YET!!" :-)
Before merging libswift's modifications need to be integrated in the libswift/devel branch.
Unfortunately updating the API means updating dispersy/tribler/libswift at the same time.

**Comment by whirm** [comment]
@badrock  gave me the OK to merge this.

**Pull request merged**
