### PR TITLE
Reduce pylint warnings.

### PR DESCRIPTION
**Pull request by boudewijn-tribler**

### CODE REVIEW

**Comment by boudewijn-tribler** [comment]
retest this please

**Comment by boudewijn-tribler** [comment]
Won't build since the Jenkins config for skip, prune, and clean changed.  I can revert the changes, but it was probably changed to fix something else?  @whirm, any wise words?

**Comment by whirm** [comment]
@boudewijn-tribler  it says:
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.

It's not even able to check out the code

**Comment by whirm** [comment]
retest this please

**Comment by boudewijn-tribler** [comment]
So that was Jenkins fluke?  Because I didn't do anything since the last fail...

**Comment by whirm** [comment]
Yes, I had to wipe the workspace out.

**Pull request merged**
