### PR TITLE
Fixed updating tunnel Candidate sock address magic number

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes https://github.com/Tribler/tribler/issues/1623.

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by qstokkink** [comment]
Eh? `ERROR: [GitHub Commit Status Setter] - {"message":"No commit found for SHA: 061d4cb820576bb02f7398c554be2b5e5475732f","documentation_url":"https://developer.github.com/v3/repos/statuses/"}, setting build result to FAILURE`

EDIT: Oh, this seems to be normal execution, judging by the other PRs

**Comment by qstokkink** [comment]
@devos50 ready for review

**Comment by devos50** [comment]
@qstokkink thanks!

**Pull request merged**
