### PR TITLE
Move on_incoming_packets, batching and its auxiliar functions to community.py

### PR DESCRIPTION
**Pull request by whirm**
Also remove obsoleted tests.

### CODE REVIEW

**Comment by whirm** [comment]
@NielsZeilemaker This merge broke (at least) the tests in debug mode.

**Comment by NielsZeilemaker** [comment]
I can't see it, I only see the expected failure in the bootstrap server test.  Please explain

**Comment by whirm** [comment]
The unit tests are first run in optimized mode, and if they pass in debug mode trough nose with coverage, etc...
As the optimized run failed because of the flaky VU trackers, it didn't run the one in debug mode.
I'm sending a pull request to work around the fascist asserts but we should talk about redoing those, it's ridiculous to have to unwind an iterator into a list to pass it to a function that will iterate over it.

**Comment by NielsZeilemaker** [comment]
"facist asserts" classy :smile:

2014/1/24 Elric Milon notifications@github.com

**Pull request merged**
