### PR TITLE
Catch an OSError from netifaces

### LINKED ISSUE #448: netiface error
Check https://github.com/Tribler/tribler/issues/1575

Looks like `netifaces.interfaces()` caused the problem. I checked netifaces code and found that an underlying function may raise an `OSError` if `GetAdaptersAddresses()` fails. So I guess we need to catch `OSError` on `netifaces.interfaces()`.

### PR DESCRIPTION
**Pull request by LipuFei**
Closes #448

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm ready

**Comment by whirm** [comment]
This should go against `next`

**Comment by LipuFei** [comment]
Ok, I thought we are still on `devel` with dispersy

**Comment by LipuFei** [comment]
@whirm Wait, I just checked. It should be `devel`. the latest commits in `next` are all from 2 years ago.

**Comment by whirm** [comment]
yeah, sorry, I don't know what I was thinking :D

**Pull request merged**
