### PR TITLE
fix unicodes

### PR DESCRIPTION
**Pull request by ghost**
dispersy throws typeerror for unicode addresses and payloads, here are small fixes not sure it is the root cause

### CODE REVIEW

**Comment by devos50** [comment]
add to whitelist

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
ok to test

**Comment by synctext** [comment]
ok to test

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
@boogiepy can you provide some more information about this error? On which platform does it happen?

**Comment by egbertbouman** [comment]
I prefer a solution where all IP address are either unicode or str. So, I'm closing this one in favor of https://github.com/Tribler/dispersy/pull/525.

**Pull request closed without merging**
