### PR TITLE
Test for wan_voting

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
No clue where to put this one, hence I create a new test file. #102

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
The test is triggering the bug now, should work after Boudewijn's fix is merged.

**Comment by NielsZeilemaker** [comment]
retest this please

**Comment by boudewijn-tribler** [comment]
Thanks for making the test, but can you add a test description please.

**Comment by NielsZeilemaker** [comment]
I will, any idea on a name for the test? I don't think there's a unit test for the nat type detection logic right? 
Maybe test_nat_detection.py?

**Comment by boudewijn-tribler** [comment]
The only existing test that comes close is test_walker.py (as the nat detection occurs during the walker), but adding a new test makes more sense.  Your proposed name sounds good.

**Pull request merged**
