### PR TITLE
RequestCache bug unittest

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Unittest which is triggering the bug as reported in Tribler/dispersy#3 and Tribler/dispersy#7

### CODE REVIEW

**Comment by boudewijn-tribler** [comment]
If we add the `unittest.expectFailure` decorator we can merge this pull.  We can remove the decorator once it is fixed.

http://docs.python.org/2/library/unittest.html#skipping-tests-and-expected-failures

**Comment by NielsZeilemaker** [comment]
Doesn't make sense to me. It's a bug which is causing problems during my experiments for over 4 months already. This needs to be fixed asap.

**Comment by whirm** [comment]
@boudewijn-tribler, @NielsZeilemaker: Any news on this?

**Comment by whirm** [comment]
According to @boudewijn-tribler  #106 fixes this among other things. (But also changes the API and breaks Tribler and I guess @NielsZeilemaker scenarios.)

@NielsZeilemaker Do you agree #106 supersedes this pull request?

**Comment by NielsZeilemaker** [comment]
Be my guest, I don't mind what the solution will be. As long as it gets fixed.

**Pull request closed without merging**
