### PR TITLE
Fix TasteBuddy.__cmp__

### LINKED ISSUE #358: TypeError: object of type 'int' has no len()
This happened on Tribler 6.3.0 RC2 instance close:

```
ERROR   1407361024.10        dispersy:1724  exception during handle_callback for similarity-response
Traceback (most recent call last):
  File "/home/vvs/tribler/Tribler/dispersy/dispersy.py", line 1719, in _update
    messages[0].handle_callback(messages)
  File "/home/vvs/tribler/Tribler/dispersy/discovery/community.py", line 556, in on_similarity_response
    destination, introduce_me_to = self.get_most_similar(w_candidate)
  File "/home/vvs/tribler/Tribler/dispersy/discovery/community.py", line 385, in get_most_similar
    self.clean_possible_taste_buddies()
  File "/home/vvs/tribler/Tribler/dispersy/discovery/community.py", line 367, in clean_possible_taste_buddies
    to_low_sim = self.possible_taste_buddies[i] <= low_sim
  File "/home/vvs/tribler/Tribler/dispersy/discovery/community.py", line 131, in __cmp__
    return TasteBuddy.__cmp__(self, other)
  File "/home/vvs/tribler/Tribler/dispersy/discovery/community.py", line 60, in __cmp__
    return cmp(len(self.overlap), other)
TypeError: object of type 'int' has no len()
```

### PR DESCRIPTION
**Pull request by egbertbouman**
Fixes https://github.com/Tribler/dispersy/issues/358.

### CODE REVIEW

**Comment by whirm** [comment]
@egbertbouman can you send the fix to next too, please?

**Comment by egbertbouman** [comment]
@whirm Will do.

**Comment by egbertbouman** [comment]
@whirm It turns out that next does not have the DiscoveryCommunity :P

**Comment by whirm** [comment]
oh I was convinced it did... :D

**Comment by whirm** [comment]
Oh, sorry brainfart, next hasn't been updated since the middle ages.

**Pull request merged**
