### PR TITLE
Do not raise an exception if the candidate is not in self._candidates.

### PR DESCRIPTION
**Pull request by whirm**

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
@whirm we have to look into this, it doesn't make sense that other.sock_addr isn't in self._candidates as the "others" are first extracted from the self._candidate list

**Comment by whirm** [comment]
I can't reproduce it anymore, I'm closing the pull request

**Comment by NielsZeilemaker** [comment]
Do you want to commit the fix for the wrong indentation?

**Comment by whirm** [comment]
oh, true, give me a minute

**Pull request merged**
