### PR TITLE
Fixes duplicate callback identifier bug.

### PR DESCRIPTION
**Pull request by boudewijn-tribler**
Using RequestCache identifiers (which are unique per community) for
Callback identifiers (which should be unique per Dispersy) will
obviously cause conflicts.

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
Thanks, this look really nice. Are you planning to add the community identifier to all identifiers or is that a different pull request?

**Comment by NielsZeilemaker** [comment]
Nevermind, that isn't neccesary anymore.

**Comment by boudewijn-tribler** [comment]
I wasn't planning on doing that at all tbh, now that the `RequestCache` is unique per community it doesn't require the community id in the identifier string.  Or do you have a use case in mind where this would be useful?

**Comment by boudewijn-tribler** [comment]
Ah ok :)

**Pull request merged**
