### PR TITLE
Callback.call will now propagate the exception with the callstack.

### PR DESCRIPTION
**Pull request by boudewijn-tribler**
Implements: https://github.com/Tribler/dispersy/issues/59

### CODE REVIEW

**Comment by boudewijn-tribler** [comment]
Segfault.  This is probably the nosetests coverage reporter again.  Elric, can you verify?

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
[11044225.735992] nosetests[26155]: segfault at 51 ip 00007f867c6941e9 sp 00007f867c0466d0 error 4 in libsqlite3.so.0.8.6[7f867c672000+aa000]

Sqlite is segfaulting :(

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
Yay, upgraded to latest sqlite (3.7.17) from unstable and it doesn't segfault anymore. 
Lets test again just in case.

retest this please

**Comment by boudewijn-tribler** [comment]
retest this please

**Comment by boudewijn-tribler** [comment]
fixes #59

**Pull request merged**
