### PR TITLE
Per-class logger

### PR DESCRIPTION
**Pull request by LipuFei**
Use per-class logger.

### CODE REVIEW

**Comment by LipuFei** [comment]
@whirm I think this should be it. I've rearranged the order of the commits, so e69fb04 is actually the last commit.

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
@LipuFei some lines got over 120 chars with your updates, could you fix that? 
I noticed pylint wasn't finding its config file, I'm fixing that now.

**Comment by whirm** [comment]
Other than that looks OK to me

**Comment by LipuFei** [comment]
@whirm I've solved most of those pep8 problems.

**Pull request merged**
