### PR TITLE
Added yappi as twistd profiler

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
@whirm @lfdversluis can one of you give me permission to test?

**Comment by devos50** [comment]
Also, @lfdversluis can you review?

**Comment by lfdversluis** [comment]
ok to test

**Comment by lfdversluis** [comment]
add to whitelist

**Comment by devos50** [comment]
@whirm can you give me access to test?

**Comment by lfdversluis** [comment]
I see my code again, I am not the right person to review. You should actually review it!

**Comment by devos50** [comment]
Yeah that's true, @whirm maybe you can review it (you've probably already seen this code).

**Comment by whirm** [comment]
add to whitelist

**Comment by whirm** [comment]
looks fine to me

**Comment by devos50** [comment]
@whirm tests are passing ;)

**Pull request merged**
